# -*- coding: utf-8 -*-
"""C_VS_Q Conference_DataPreprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nS4ECiLDJ98eHeJApaP0DD0IfCtrDq8x
"""

#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Minimal, academic-ready preprocessing for deep sequence models (strictly sequential; no missing-data imputation).

Pipelines included:
  - BASE   : numeric features only
  - Y_LAGS : BASE + autoregressive lags of ALL target columns (strictly causal)

Design:
  - Assumes the source CSV has **no missing values** (we do NOT fill anything)
  - If you choose Y_LAGS, we drop ONLY the initial rows that become NaN due to shifting
  - Chronological split: Train -> Val -> Test (no shuffling)
  - Optional standardization (train-only) for X and Y
  - Optional sliding-window sequences saved per requested window sizes

Outputs per pipeline:
  outdir/PIPELINE/
    X_train.npy, X_val.npy, X_test.npy
    Y_train.npy, Y_val.npy, Y_test.npy
    features.csv
    metadata.json
    [x_scaler_state.npz, y_scaler_state.npz if scaling enabled]
    Optional sequences: win{W}/Xseq_*.npy, Yseq_*.npy

Usage (Colab, zero-config if your file is in /content):
  python preprocess_base_y_lags_minimal.py --outdir "/content/artifacts_preprocessed"

Usage (PyCharm/terminal):
  python preprocess_base_y_lags_minimal.py \
      --csv "D:/data/cps_timeseries_features.csv" \
      --outdir "./artifacts_preprocessed" \
      --pipelines BASE Y_LAGS \
      --y_lags 1 2 4 8 \
      --window_sizes 32 64 \
      --scale_x --scale_y
"""

import os, math, json, argparse, warnings
from typing import Tuple, List, Dict, Optional
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

# --------------------  Train-only scaler --------------------
class Standardizer:
    """Train-only Z-score standardizer for numpy arrays."""
    def __init__(self):
        self.mean = None
        self.std = None
    def fit(self, X: np.ndarray):
        self.mean = X.mean(axis=0, keepdims=True)
        self.std  = X.std(axis=0, keepdims=True)
        self.std[self.std < 1e-12] = 1.0
        return self
    def transform(self, X: np.ndarray) -> np.ndarray:
        return (X - self.mean) / self.std
    def inverse_transform(self, Z: np.ndarray) -> np.ndarray:
        return Z * self.std + self.mean
    def save(self, path_npz: str):
        np.savez(path_npz,
                 mean=self.mean.astype(np.float32),
                 std=self.std.astype(np.float32))

# -------------------- Time utilities ------------------------------
TIMESTAMP_CANDIDATES = ["timestamp", "time", "date", "datetime"]

def find_time_column(df: pd.DataFrame) -> Optional[str]:
    for c in df.columns:
        if any(tk in c.lower() for tk in TIMESTAMP_CANDIDATES):
            return c
    return None

# -------------------- Feature engineering -------------------------
def add_y_lags(df: pd.DataFrame, targets: List[str], lags: List[int]) -> pd.DataFrame:
    """
    Create strictly-causal autoregressive features for EACH target:
      target_lagL = target.shift(L)
    NOTE: This introduces NaNs at the top; we will drop those rows.
    """
    out = df.copy()
    for L in lags:
        for t in targets:
            out[f"{t}_lag{L}"] = out[t].shift(L)
    return out

# -------------------- Splitting & sequences -----------------------
def time_splits(n: int, test_frac=0.15, val_frac=0.15) -> Tuple[int, int]:
    """Return (train_end_idx, val_end_idx) with strict chronology."""
    test_size = int(math.floor(test_frac * n))
    val_size  = int(math.floor(val_frac  * n))
    train_end = n - test_size - val_size
    val_end   = n - test_size
    if train_end <= 0 or val_end <= 0:
        raise ValueError("Notd enough rows for chosen val/test fractions.")
    return train_end, val_end

def build_sequences(X: np.ndarray, Y: np.ndarray, window: int) -> Tuple[np.ndarray, np.ndarray]:
    """
    Sliding windows in time order:
      Xs[i] = X[i : i+window]
      Ys[i] = Y[i+window-1]
    """
    n, d = X.shape
    if n < window:
        raise ValueError(f"Not enough rows ({n}) for window={window}")
    T = n - window + 1
    Xs = np.zeros((T, window, d), dtype=np.float32)
    Ys = np.zeros((T, Y.shape[1]), dtype=np.float32)
    for i in range(T):
        Xs[i] = X[i:i+window]
        Ys[i] = Y[i+window-1]
    return Xs, Ys

# -------------------- Pipeline builder ----------------------------
def build_pipeline_tables(
    base_df: pd.DataFrame,
    targets: List[str],
    pipeline: str,
    y_lags: List[int],
    test_frac: float,
    val_frac: float,
) -> Tuple[pd.DataFrame, pd.DataFrame, List[str], Dict]:
    """
    Returns:
      X_df, Y_df, feature_names, meta

    Assumptions:
      - Incoming base_df has **no missing data**
      - For Y_LAGS, we drop ONLY rows made NaN by lagging (causal)
    """
    # Keep numeric + targets (drop any non-numerics like timestamps/ids)
    for t in targets:
        if t not in base_df.columns:
            raise ValueError(f"Target '{t}' not in CSV.")
    num_cols = base_df.select_dtypes(include=[np.number]).columns.tolist()
    keep_cols = sorted(set(num_cols + targets))
    X_df = base_df[keep_cols].copy()

    # Split out Y early (no fills applied)
    Y_df = X_df[targets].copy()
    X_df = X_df.drop(columns=targets)

    meta = {"pipeline": pipeline}

    if pipeline == "BASE":
        pass

    elif pipeline == "Y_LAGS":
        # Add lags for ALL targets; then drop the initial NaN rows only
        aug = add_y_lags(pd.concat([X_df, Y_df], axis=1), targets, y_lags)
        X_df = aug.drop(columns=targets)
        Y_df = aug[targets]
        # Drop rows introduced by lagging
        X_df = X_df.dropna()
        Y_df = Y_df.loc[X_df.index]
        meta["y_lags"] = list(y_lags)

    else:
        raise ValueError("Unknown pipeline (only BASE and Y_LAGS are allowed in this script).")

    # Recompute splits AFTER any lag drop
    N = X_df.shape[0]
    train_end, val_end = time_splits(N, test_frac=test_frac, val_frac=val_frac)

    feat_cols = list(X_df.columns)
    meta.update({
        "rows_after_pipeline": int(N),
        "train_end_row": int(train_end),
        "val_end_row": int(val_end),
        "n_features": len(feat_cols),
    })
    return X_df, Y_df, feat_cols, meta

# -------------------- Main preprocessing entry --------------------
def main():
    ap = argparse.ArgumentParser(description="Strictly sequential preprocessing (BASE, Y_LAGS), no missing-data fills.")
    # Make Colab dead-simple: default to /content/cps_timeseries_features.csv
    ap.add_argument("--csv", type=str,
                    default=os.environ.get("DLCSV",r"C:\Users\Dell\Downloads\archive\Final_cps_timeseries_features.csv"))#,
                   # help="Path to raw CSV. Defaults to r C:\Users\Dell\cps_timeseries_features.csv;")
                   #         "or set env var DLCSV; or pass --csv explicitly.")
    ap.add_argument("--outdir", type=str, default="./artifacts_preprocessed")
    ap.add_argument("--targets", nargs="+", default=["Buffer_M1_M2","Buffer_M2_M3"])

    # Pipelines (as requested: PCA/EWD are excluded)
    ap.add_argument("--pipelines", nargs="+", default=["BASE","Y_LAGS"],
                    choices=["BASE","Y_LAGS"])
    ap.add_argument("--y_lags", nargs="+", type=int, default=[1])

    # Splits & scaling
    ap.add_argument("--test_frac", type=float, default=0.15)
    ap.add_argument("--val_frac", type=float, default=0.15)
    ap.add_argument("--scale_x", action="store_true")
    ap.add_argument("--scale_y", action="store_true")

    # Optional sequences to export
    ap.add_argument("--window_sizes", nargs="*", type=int, default=[32])

    args = ap.parse_args()

    # Check CSV existence early (friendly message)
    if not os.path.exists(args.csv):
        raise SystemExit(
            f"ERROR: CSV not found at: {args.csv}\n"
            "Tip (Colab): put your file at /content/cps_timeseries_features.csv and rerun without --csv\n"
            "Tip (PyCharm): pass --csv \"D:/path/cps_timeseries_features.csv\" or set DLCSV env var."
        )

    os.makedirs(args.outdir, exist_ok=True)

    # ---- Load and sort chronologically if a time column exists ----
    df_raw = pd.read_csv(args.csv, low_memory=False)
    time_col = None
    for c in df_raw.columns:
        if any(tk in c.lower() for tk in TIMESTAMP_CANDIDATES):
            time_col = c
            break
    if time_col is not None:
        try:
            df_raw[time_col] = pd.to_datetime(df_raw[time_col], errors="coerce")
            df_raw = df_raw.sort_values(time_col).reset_index(drop=True)
        except Exception:
            # If conversion fails, we just keep the current order
            pass

    # Global info
    meta_global = {
        "csv": os.path.abspath(args.csv),
        "rows_total": int(df_raw.shape[0]),
        "targets": args.targets,
        "pipelines": args.pipelines,
        "test_frac": args.test_frac,
        "val_frac": args.val_frac,
        "scale_x": bool(args.scale_x),
        "scale_y": bool(args.scale_y),
        "window_sizes": args.window_sizes,
        "note": "No missing-data imputation performed; only Y_LAGS drop of initial lagged rows."
    }

    all_pipeline_meta = []

    # ---- Process each pipeline ----
    for pipe in args.pipelines:
        print(f"\n[PIPELINE] {pipe}")
        X_df, Y_df, feat_cols, pmeta = build_pipeline_tables(
            base_df=df_raw,
            targets=args.targets,
            pipeline=pipe,
            y_lags=args.y_lags,
            test_frac=args.test_frac,
            val_frac=args.val_frac,
        )

        # Split after pipeline
        N = X_df.shape[0]
        train_end, val_end = time_splits(N, test_frac=args.test_frac, val_frac=args.val_frac)
        X_all = X_df.values.astype(np.float32)
        Y_all = Y_df.values.astype(np.float32)
        # --- FORWARD-FILL MISSING VALUES IN TARGETS ---
        # Convert to DataFrame for convenience
        Y_ffill = pd.DataFrame(Y_all, columns=Y_df.columns)
        # Forward-fill
        Y_ffill = Y_ffill.fillna(method='ffill')
        # Fill any leading NaNs with 0 (or another value if preferred)
        Y_ffill = Y_ffill.fillna(0)
        # Convert back to numpy
        Y_all = Y_ffill.values.astype(np.float32)
        X_tr_raw, X_val_raw, X_te_raw = X_all[:train_end], X_all[train_end:val_end], X_all[val_end:]
        Y_tr_raw, Y_val_raw, Y_te_raw = Y_all[:train_end], Y_all[train_end:val_end], Y_all[val_end:]

        # Train-only scaling (optional)
        Xsc = None
        if args.scale_x:
            Xsc = Standardizer().fit(X_tr_raw)
            X_tr = Xsc.transform(X_tr_raw); X_val = Xsc.transform(X_val_raw); X_te = Xsc.transform(X_te_raw)
        else:
            X_tr, X_val, X_te = X_tr_raw, X_val_raw, X_te_raw

        Ysc = None
        if args.scale_y:
            Ysc = Standardizer().fit(Y_tr_raw)
            Y_tr = Ysc.transform(Y_tr_raw); Y_val = Ysc.transform(Y_val_raw); Y_te = Ysc.transform(Y_te_raw)
        else:
            Y_tr, Y_val, Y_te = Y_tr_raw, Y_val_raw, Y_te_raw

        # Save matrices
        pdir = os.path.join(args.outdir, pipe)
        os.makedirs(pdir, exist_ok=True)
        np.save(os.path.join(pdir, "X_train.npy"), X_tr)
        np.save(os.path.join(pdir, "X_val.npy"),   X_val)
        np.save(os.path.join(pdir, "X_test.npy"),  X_te)
        np.save(os.path.join(pdir, "Y_train.npy"), Y_tr)
        np.save(os.path.join(pdir, "Y_val.npy"),   Y_val)
        np.save(os.path.join(pdir, "Y_test.npy"),  Y_te)
        pd.DataFrame({"feature": feat_cols}).to_csv(os.path.join(pdir, "features.csv"), index=False)

        if Xsc is not None:
            Xsc.save(os.path.join(pdir, "x_scaler_state.npz"))
        if Ysc is not None:
            Ysc.save(os.path.join(pdir, "y_scaler_state.npz"))

        # Optional windowed sequences (strict order)
        seq_meta = []
        X_full = np.vstack([X_tr, X_val, X_te])
        Y_full = np.vstack([Y_tr, Y_val, Y_te])

        for w in (args.window_sizes or []):
            try:
                X_seq, Y_seq = build_sequences(X_full, Y_full, w)
                
            except ValueError:
                print(f"[WARN] window={w}: not enough rows; skipping.")
                continue

            # Map to TR/VAL/TEST indexes in sequence space
            def s_end(n_end, ww): return n_end - (ww - 1)
            tr_s_end = s_end(X_tr.shape[0]-1, w)
            va_s_end = s_end((X_tr.shape[0]+X_val.shape[0])-1, w)
            if tr_s_end < 0 or va_s_end < 0:
                print(f"[WARN] window={w}: mapping failed; skipping.")
                continue

            X_tr_s, Y_tr_s = X_seq[:tr_s_end+1], Y_seq[:tr_s_end+1]
            X_va_s, Y_va_s = X_seq[tr_s_end+1:va_s_end+1], Y_seq[tr_s_end+1:va_s_end+1]
            X_te_s, Y_te_s = X_seq[va_s_end+1:],           Y_seq[va_s_end+1:]

            wdir = os.path.join(pdir, f"win{w}")
            os.makedirs(wdir, exist_ok=True)
            np.save(os.path.join(wdir, "Xseq_train.npy"), X_tr_s)
            np.save(os.path.join(wdir, "Xseq_val.npy"),   X_va_s)
            np.save(os.path.join(wdir, "Xseq_test.npy"),  X_te_s)
            np.save(os.path.join(wdir, "Yseq_train.npy"), Y_tr_s)
            np.save(os.path.join(wdir, "Yseq_val.npy"),   Y_va_s)
            np.save(os.path.join(wdir, "Yseq_test.npy"),  Y_te_s)
            seq_indices = np.arange(len(Y_full))  # original indices corresponding to each sequence
            np.save(os.path.join(wdir, "seq_indices.npy"), seq_indices)
            seq_meta.append({"window": w,
                "Xseq_train_shape": list(X_tr_s.shape),
                "Xseq_val_shape":   list(X_va_s.shape),
                "Xseq_test_shape":  list(X_te_s.shape),})

        # Pipeline metadata
        meta = {"pipeline": pipe,"features": feat_cols,
            "X_train_shape": list(X_tr.shape),
            "X_val_shape":   list(X_val.shape),
            "X_test_shape":  list(X_te.shape),
            "Y_train_shape": list(Y_tr.shape),
            "Y_val_shape":   list(Y_val.shape),
            "Y_test_shape":  list(Y_te.shape),
            "train_end_row": int(train_end),
            "val_end_row":   int(val_end),
            "scale_x": bool(args.scale_x),
            "scale_y": bool(args.scale_y),
            "sequences": seq_meta,**pmeta}
        with open(os.path.join(pdir, "metadata.json"), "w", encoding="utf-8") as f:
            json.dump(meta, f, indent=2)
        all_pipeline_meta.append(meta)

    # Root metadata
    with open(os.path.join(args.outdir, "meta_global.json"), "w", encoding="utf-8") as f:
        json.dump({**meta_global, "pipelines_summary": all_pipeline_meta}, f, indent=2)

    print("\n[OK] Preprocessing complete.")
    print(f"  Outdir: {os.path.abspath(args.outdir)}")
    for pipe in args.pipelines:
        print(f"  - {pipe}/ -> X_*.npy, Y_*.npy, features.csv, metadata.json, scaler states (if scaled)")
        if args.window_sizes:
            print(f"    sequences under {pipe}/win*/  (Xseq_*.npy, Yseq_*.npy)")

if __name__ == "__main__":
    main()